name: The New Zazzup
favicon: null
layout_spectrum: 0.9074860946275294
typography_spectrum: 0.7234008121304214
title: 'Zazzup by iFundSharing, LLC'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2956ea'
    - '#25cc06'
    - '#ffffff'
    - '#0a163b'
    - '#bccaf8'
  brandStrength: 0.5
  lightness: 0.6478275721892715
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
