name: The New Zazzup
favicon: null
layout_spectrum: 0.9074860946275294
typography_spectrum: 0.7234008121304214
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7342288268264383
  lightness: 0.6478275721892715
  saturation: 0.9502090928144753
  rhythmicContrast: 0.09957835171371698
purpose: []
